all: mx_tcp_server tcp_client tcp_server

mx_tcp_server: mx_tcp_server.c
	gcc -o mx_tcp_server  mx_tcp_server.c

tcp_client: tcp_client.c
	gcc -o tcp_client tcp_client.c

tcp_server: tcp_server.c
	gcc -o tcp_server tcp_server.c
